package ghosts;

import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class CrearPlayer extends javax.swing.JFrame {
    
    Login login;
    Player player;
    /**
     * Creates new form VentanaRegistrarse
     */
    public CrearPlayer(Login login, Player player) {
        initComponents();
        setLocationRelativeTo(this);
        
        this.login=login;
        this.player=player;
        setResizable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioRegistro = new javax.swing.JTextField();
        txtContraRegistro = new javax.swing.JPasswordField();
        crearCuentaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogin1.setBackground(new java.awt.Color(0, 102, 102));
        btnlogin1.setFont(new java.awt.Font("Papyrus", 3, 28)); // NOI18N
        btnlogin1.setForeground(new java.awt.Color(0, 0, 0));
        btnlogin1.setText("Regresar");
        btnlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 156, 68));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 244, -1, -1));
        jPanel1.add(txtUsuarioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 244, 36));

        txtContraRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 244, 37));

        crearCuentaButton.setBackground(new java.awt.Color(0, 102, 102));
        crearCuentaButton.setFont(new java.awt.Font("Papyrus", 3, 28)); // NOI18N
        crearCuentaButton.setForeground(new java.awt.Color(0, 0, 0));
        crearCuentaButton.setText("Crear Player");
        crearCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(crearCuentaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 210, 50));

        jLabel2.setFont(new java.awt.Font("Papyrus", 3, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Player");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Papyrus", 3, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Papyrus", 3, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/registrofondo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogin1ActionPerformed
        MenuDeInicio menudeinicio = new MenuDeInicio(login, player);
        menudeinicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogin1ActionPerformed

    private void txtContraRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraRegistroActionPerformed

    private void crearCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaButtonActionPerformed
        //Iniciar creacion de usuarios
        String user = txtUsuarioRegistro.getText();
        String contrasena = new String(txtContraRegistro.getPassword());
        String logs="";
        int puntos=0;
        Usuarios usuarios = new Usuarios(user,contrasena,puntos, logs);
            if(txtUsuarioRegistro.getText().isEmpty() || txtContraRegistro.getPassword().length<1){
                JOptionPane.showMessageDialog(null, "Ingrese usuario y contraseña.");
            }else{
                //Guardar usuarios
                boolean respuesta = login.getControlador().agregarUsuario(usuarios);
                if(respuesta == true) {
                    player.totalUsuariosActivos++;
                    player.totalUsuariosHistoricos++;
                    JOptionPane.showMessageDialog(null, "Se ha registrado correctamente.");
                    player.usuarioLogeado=user;
                    player.modo="AZAR";
                    player.dificultad="NORMAL";
                    MenuPrincipal menuprincipal = new MenuPrincipal(login, player);
                    menuprincipal.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "El usuario ya existe.");
                }
            }
        

    }//GEN-LAST:event_crearCuentaButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin1;
    private javax.swing.JButton crearCuentaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraRegistro;
    private javax.swing.JTextField txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
