package ghosts;

public class MenuPrincipal extends javax.swing.JFrame {
    Login login;
    Player player;
    
    public MenuPrincipal(Login login, Player player) {
        initComponents();
        this.login=login;
        this.player=player;
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnjugarghosts = new javax.swing.JButton();
        btncerrarsesion = new javax.swing.JButton();
        btnconfiguracion = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btnmiperfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnjugarghosts.setBackground(new java.awt.Color(149, 64, 35));
        btnjugarghosts.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnjugarghosts.setForeground(new java.awt.Color(0, 0, 0));
        btnjugarghosts.setText("Jugar Ghosts");
        btnjugarghosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarghostsActionPerformed(evt);
            }
        });
        jPanel1.add(btnjugarghosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 210, 68));

        btncerrarsesion.setBackground(new java.awt.Color(149, 64, 35));
        btncerrarsesion.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btncerrarsesion.setForeground(new java.awt.Color(0, 0, 0));
        btncerrarsesion.setText("Cerrar Sesion");
        btncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(btncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 68));

        btnconfiguracion.setBackground(new java.awt.Color(149, 64, 35));
        btnconfiguracion.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnconfiguracion.setForeground(new java.awt.Color(0, 0, 0));
        btnconfiguracion.setText("Configuracion");
        btnconfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfiguracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnconfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 68));

        btnreportes.setBackground(new java.awt.Color(149, 64, 35));
        btnreportes.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(0, 0, 0));
        btnreportes.setText("Reportes");
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 210, 68));

        btnmiperfil.setBackground(new java.awt.Color(149, 64, 35));
        btnmiperfil.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnmiperfil.setForeground(new java.awt.Color(0, 0, 0));
        btnmiperfil.setText("Mi Perfil");
        btnmiperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmiperfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnmiperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 210, 68));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoprincipal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjugarghostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarghostsActionPerformed
        PedirSegundoPlayer psp = new PedirSegundoPlayer(player, login);
        psp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnjugarghostsActionPerformed

    private void btncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarsesionActionPerformed
        MenuDeInicio menudeinicio = new MenuDeInicio(login, player);
        menudeinicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncerrarsesionActionPerformed

    private void btnconfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfiguracionActionPerformed
    Configuracion configuracion = new Configuracion(login, player);
    configuracion.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnconfiguracionActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        Reportes reportes = new Reportes(login, player);
        reportes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnreportesActionPerformed

    private void btnmiperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmiperfilActionPerformed
        MiPerfil miperfil = new MiPerfil(login, player);
        miperfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmiperfilActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrarsesion;
    private javax.swing.JButton btnconfiguracion;
    private javax.swing.JButton btnjugarghosts;
    private javax.swing.JButton btnmiperfil;
    private javax.swing.JButton btnreportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
