/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

/**
 *
 * @author danie
 */
public class MenuDeInicio extends javax.swing.JFrame {
    Login login;
    Player player;
    
    /**
     * Creates new form MenuDeInicio
     */
    public MenuDeInicio(Login login, Player player) {
        initComponents();
        this.login=login;
        this.player=player;
        player.dificultad="NORMAL";
        setLocationRelativeTo(this);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        crearPlayerBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(51, 51, 51));
        loginButton.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 207, 68));

        crearPlayerBoton.setBackground(new java.awt.Color(51, 51, 51));
        crearPlayerBoton.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        crearPlayerBoton.setForeground(new java.awt.Color(0, 0, 0));
        crearPlayerBoton.setText("Crear Player");
        crearPlayerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPlayerBotonActionPerformed(evt);
            }
        });
        jPanel1.add(crearPlayerBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 207, 68));

        salirBoton.setBackground(new java.awt.Color(51, 51, 51));
        salirBoton.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        salirBoton.setForeground(new java.awt.Color(0, 0, 0));
        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });
        jPanel1.add(salirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 207, 68));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoinicio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        Login login = new Login(player);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void crearPlayerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPlayerBotonActionPerformed
        CrearPlayer crearplayer = new CrearPlayer(login, player);
        crearplayer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearPlayerBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBotonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearPlayerBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton salirBoton;
    // End of variables declaration//GEN-END:variables
}
