/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class MiPerfil extends javax.swing.JFrame {
    Login login;
    Player player;
    /**
     * Creates new form MiPerfil
     */
    public MiPerfil(Login login, Player player) {
        initComponents();
        this.login=login;
        this.player=player;
        lblusuariologeado.setText(player.usuarioLogeado);
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblusuariologeado = new javax.swing.JLabel();
        btnregresarconfig = new javax.swing.JButton();
        btndificultadexperto = new javax.swing.JButton();
        btnmodomanual1 = new javax.swing.JButton();
        btnmodomanual2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusuariologeado.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        lblusuariologeado.setForeground(new java.awt.Color(255, 255, 255));
        lblusuariologeado.setText("user");
        jPanel1.add(lblusuariologeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 62));

        btnregresarconfig.setBackground(new java.awt.Color(102, 102, 102));
        btnregresarconfig.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnregresarconfig.setForeground(new java.awt.Color(0, 0, 0));
        btnregresarconfig.setText("Regresar");
        btnregresarconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarconfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresarconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 170, 60));

        btndificultadexperto.setBackground(new java.awt.Color(102, 102, 102));
        btndificultadexperto.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btndificultadexperto.setForeground(new java.awt.Color(0, 0, 0));
        btndificultadexperto.setText("Ver mis datos");
        btndificultadexperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndificultadexpertoActionPerformed(evt);
            }
        });
        jPanel1.add(btndificultadexperto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 207, 60));

        btnmodomanual1.setBackground(new java.awt.Color(102, 102, 102));
        btnmodomanual1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnmodomanual1.setForeground(new java.awt.Color(0, 0, 0));
        btnmodomanual1.setText("Eliminar mi cuenta");
        btnmodomanual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodomanual1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodomanual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 270, 60));

        btnmodomanual2.setBackground(new java.awt.Color(102, 102, 102));
        btnmodomanual2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnmodomanual2.setForeground(new java.awt.Color(0, 0, 0));
        btnmodomanual2.setText("Cambiar Password");
        btnmodomanual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodomanual2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodomanual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 270, 60));

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mi Perfil");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 62));

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario logeado: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 62));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondomiperfil.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 740, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarconfigActionPerformed
        MenuPrincipal menuprincipal = new MenuPrincipal(login, player);
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregresarconfigActionPerformed

    private void btndificultadexpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndificultadexpertoActionPerformed
        JOptionPane.showMessageDialog(null, "Cuenta: "+player.usuarioLogeado+"\nPuntos: "+player.buscarUsuario(player.usuarioLogeado, 0).getPuntos());
    }//GEN-LAST:event_btndificultadexpertoActionPerformed

    private void btnmodomanual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodomanual1ActionPerformed
        EliminarMiCuenta emc = new EliminarMiCuenta(login, player);
        emc.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnmodomanual1ActionPerformed

    private void btnmodomanual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodomanual2ActionPerformed
        CambiarPassword cambiarpassword = new CambiarPassword(login, player);
        cambiarpassword.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnmodomanual2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndificultadexperto;
    private javax.swing.JButton btnmodomanual1;
    private javax.swing.JButton btnmodomanual2;
    private javax.swing.JButton btnregresarconfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblusuariologeado;
    // End of variables declaration//GEN-END:variables
}
