/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghosts;

import ghosts.Usuarios.UsuarioComparator;
import java.util.Collections;

/**
 *
 * @author danie
 */
public class Reportes extends javax.swing.JFrame {
    Login login;
    Player player;
    UsuarioComparator usuarioComparator = new UsuarioComparator();
    
    public Reportes(Login login, Player player) {
        initComponents();
        this.login=login;
        this.player=player;
        tahistorialjuegos.setText(player.buscarUsuario(player.usuarioLogeado, 0).getLogs());
                
        // Ordenar la lista de usuarios utilizando el UsuarioComparator
        Collections.sort(player.listaUsuarios, usuarioComparator);

        // Construir el texto del ranking
        String texto = "";
        for (int i = 0; i < player.listaUsuarios.size(); i++) {
            Usuarios usuario = player.listaUsuarios.get(i);
            texto += (i + 1) + "\t" + usuario.getUser() + "\t" + usuario.getPuntos() + "\n";
        }
        
        taranking.setEditable(false);
        tahistorialjuegos.setEditable(false);
        taranking.setText(texto);
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnregresarconfig = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taranking = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tahistorialjuegos = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 62));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ranking de Jugadores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 62));

        btnregresarconfig.setBackground(new java.awt.Color(153, 0, 0));
        btnregresarconfig.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnregresarconfig.setForeground(new java.awt.Color(0, 0, 0));
        btnregresarconfig.setText("Regresar");
        btnregresarconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarconfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresarconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 170, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion de mis ultimos 10 juegos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 460, 60));

        taranking.setBackground(new java.awt.Color(102, 0, 51));
        taranking.setColumns(20);
        taranking.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        taranking.setForeground(new java.awt.Color(255, 255, 255));
        taranking.setRows(5);
        jScrollPane1.setViewportView(taranking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 790, 160));

        tahistorialjuegos.setBackground(new java.awt.Color(102, 0, 51));
        tahistorialjuegos.setColumns(20);
        tahistorialjuegos.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        tahistorialjuegos.setForeground(new java.awt.Color(255, 255, 255));
        tahistorialjuegos.setRows(5);
        jScrollPane2.setViewportView(tahistorialjuegos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 800, 160));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Papyrus", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  POSICION              -             USERNAME        -    PUNTOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoranking (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarconfigActionPerformed
        MenuPrincipal menuprincipal = new MenuPrincipal(login, player);
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregresarconfigActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresarconfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tahistorialjuegos;
    private javax.swing.JTextArea taranking;
    // End of variables declaration//GEN-END:variables
}
